name: Deploy VM using Github Actions
#on: push
jobs:
  DeployVM:
    runs-on: ubuntu-latest
    steps:
       - name: checkout-repository
         uses: actions/checkout@v4
       - run:  
            ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'
       - name: deployVM
         env:
           RESOURCE_GROUP: rg-githubitpro

           RESOURCE_GROUP_REGION: southcentralus

           SERVER_NAME: gihtubactions

           ADMIN_LOGIN: sarah
         run: >

            powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'"

            -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}

            -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

            -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}

            -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            -resourceGroupName %RESOURCE_GROUP%

            -resourceGroupNameRegion %RESOURCE_GROUP_REGION%

            -serverName %SERVER_NAME%

            -adminLogin %ADMIN_LOGIN%

            -adminPassword ${{ secrets.ADMIN_PASSWORD }}
